// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace HandyTools
{
    internal sealed partial class Vsix
    {
        public const string Id = "HandyTools.d11999cd-7bb6-4de2-acfc-9992c548ed34";
        public const string Name = "HandyTools";
        public const string Description = @"Some tools for editing codes";
        public const string Language = "en-US";
        public const string Version = "0.5.3";
        public const string Author = "taqu29";
        public const string Tags = "Encoding,UTF8,Line endings,CR,CRLF,LF,AI,Doxygen";
    }
}
