// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace HandyTools
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string HandyToolsString = "daafe9b8-3dc3-4cb6-a2ce-3959212fdc7c";
        public static Guid HandyTools = new Guid(HandyToolsString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int CommandCompletion = 0x0000;
        public const int CommandShowChatWindow = 0x0001;
    }
}