// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace HandyTools
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string HandyToolsString = "daafe9b8-3dc3-4cb6-a2ce-3959212fdc7c";
        public static Guid HandyTools = new Guid(HandyToolsString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int HandyTools_MenuGroup = 0x1000;
        public const int HandyTools_CommandGroup = 0x1001;
        public const int HandyTools_Menu = 0x1002;
        public const int HandyTools_ViewMenuGroup = 0x1003;
        public const int HandyTools_ViewCommandGroup = 0x1004;
        public const int HandyTools_ViewMenu = 0x1005;
        public const int CommandShowChatWindow = 0x0000;
        public const int CommandCompletion = 0x0001;
        public const int CommandExplanation = 0x0002;
        public const int CommandTranslation = 0x0003;
        public const int CommandTranslateAndReplace = 0x0004;
        public const int CommandAddDocument = 0x0005;
        public const int CommandPreviewDocument = 0x0006;
    }
}